# DataSource Settings
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=hitesh2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

#Security
logging.level.org.springframework.security=DEBUG
logging.level.org.substring.auth.auth_app_backend=DEBUG


jwt.secret=0747977c89aa6143df7766e33596cb041066df6346ac9e5c0d9a5d83f7a97810
jwt.access-token.expiration=172800000
jwt.issuer=auth-app-backend
jwt.refresh-token.expiration=604800000
jwt.refresh-token.cookie-name=REFRESH_TOKEN
jwt.cookie-secure=true
jwt.cookie-http-only=true
jwt.cookie-domain=localhost
jwt.cookie-same-site=lax